# Try and Except Block
Used to catch an exception in a python code


**Follow the following example**
```python
age = int(input("How old are you?"))
if age > 18:
    print("you can drive at age {age}")
```
The above code looks like it only takes input in form of integer but we can also input a string e.g., twelve. And when the int function outside the input function will try to convert the string i.e., twelve it won't be able to do that. and it will throw an error.

```
How old are you?twelve
Traceback (most recent call last):
  File "/home/neurocoder/coding/python/day_13/test.py", line 1, in <module>
    age = int(input("How old are you?"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'twelve'
```
**Value Error** happens with you're inputing the wrong value. 
Now how to handle this sort of error? You can just directly prompt the user in your message to enter an integer but that doesn't really solve any problem. You are still in trouble if someone accidentaly or on purpose inputs a string.
So, To strengthen your code you can use **TRY and EXCEPT Block** 
**Demonstration**
```python
try: 
age=int(input("How old are you?")) 
except ValueError: 
print("You have given an invalid input. Please give a numerical input e.g., 21")
age = int(input("How old are you?")) 
if age > 18: 
print("You can drive at age (age).")
```
The **try block** wraps code that might cause an error. If no error occurs, the code runs normally. If an error happens, Python jumps to the **except block** instead of crashing.
So if you give a wrong input the print statement in the except block will be printed in your console.

```
output = How old are you?twenty
         You have given an invalid input. Please give a numerical input e.g., 21
         How old are you?21
         You can drive at age (age).
```
This program still has a bug in it see if you can find it.